/// ═════════════════════════════════════════════════════════════
/// AUTO-GENERATED by BotForge — DO NOT EDIT MANUALLY
/// Organisation: blsxt (5b25bab0-9f07-41c9-8ed4-c08865c34f2c)
/// Generated: 2026-05-05T09:37:22.479Z
/// Chatbot ID: 96028a24-29af-4555-a452-da791b9c01e6
/// ═════════════════════════════════════════════════════════════
library;

class AppConfig {
  AppConfig._();

  // ── Brand Identity ──────────────────────────────────────────────
  static const String businessName   = 'blsxt';
  static const String tagline        = '';
  static const String botName        = 'Assistant';
  static const String botRole        = 'Customer Experience Assistant';
  static const String welcomeMessage = 'Hi there! 👋 I\'m $botName, your personal assistant at $businessName. How can I help you today?';

  static const List<String> quickReplies = [
    '💰 Pricing & Plans',
    '🛠️ Our Services',
    '📞 Contact Support'
  ];

  // ── Visuals ──────────────────────────────────────────────────────
  static const String primaryColorHex = '#6C63FF';
  static const String accentColorHex  = '#FF6584';
  static const String botAvatarAsset  = 'assets/images/bot_avatar.png';
  static const String logoAsset       = 'assets/images/logo.png';

  // ── Backend ──────────────────────────────────────────────────────
  static const String apiBaseUrl     = 'https://chat-dev-main-backend-latest-7hxy.onrender.com';
  static const String chatEndpoint   = '/chatbots/mobile';
  static const String organisationId = '5b25bab0-9f07-41c9-8ed4-c08865c34f2c';
  static const String chatbotId = '96028a24-29af-4555-a452-da791b9c01e6';
  static const String botCreatorUrl = 'https://botcreator-1.onrender.com';
  static const String apiKey = 'D6AjXcOrYSwPgd6QYu2CWLv371J1Ol2i';

  // ── Chat Session ────────────────────────────────────────────────
  static const String chatId = '';  // Generated on first chat

  // ── Business Hours ───────────────────────────────────────────────
  static const bool   showBusinessHours = false;
  static const String businessHours     = '';
  static const String offlineMessage    =
      'We are currently outside business hours. I will still do my best to help, '
      'but a human agent will follow up. 🌙';

  // ── Social / Contact ─────────────────────────────────────────────
  static const String whatsappNumber  = '';
  static const String telegramHandle  = '';
  static const String supportEmail    = '';
  static const String websiteUrl      = '';

  // ── Feature Flags ─────────────────────────────────────────────────
  static const bool enableFileAttachments = true;
  static const bool enableVoiceMessages   = false;
  static const bool enableRatings         = true;
  static const bool enableTypingIndicator = true;
  static const bool enableReadReceipts    = true;
}